In [1]:
%config Completer.use_jedi=False

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [18]:
device = torch.device('cuda')

In [15]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(3, 6)
        self.fc2 = nn.Linear(6, 3)
    
    def forward(self, x):
        x = nn.ReLU()(self.fc1(x))
        x = self.fc2(x)
        return x

In [21]:
net = Net()
net = net.to(device)

optimizer = optim.Adam(net.parameters())

In [4]:
batch_size = 32

In [22]:
num_epochs = 10000

In [30]:
def calculate_loss(net_in, net_out):
    assert net_in.shape == (batch_size, 3)
    assert net_out.shape == (batch_size, 3)
    arr_in = net_in.cpu().detach().numpy()
    arr_out = net_out.cpu().detach().numpy()
    return (np.ones((batch_size, 3)) - (arr_out - arr_in)) ** 2

In [13]:
def test_calculate_loss():
    net_in = torch.zeros((batch_size, 3))
    net_out = torch.ones((batch_size, 3)) * -4
    print(calculate_loss(net_in, net_out))

test_calculate_loss()

[[25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]
 [25. 25. 25.]]


In [32]:
for epoch in range(num_epochs):
    batch = torch.randn((batch_size, 3)).to(device)
    batch_out = net(batch)
    
    optimizer.zero_grad()
    loss = calculate_loss(batch, batch_out)
    torch.tensor(loss).backward()
    optimizer.step()
    
    if epoch % 1000 == 0:
        print(f'epoch = {epoch}, loss = {loss}')

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn